###########
# site.title, site.url, site.author.name

title:   'Tales from a Mage'
author:
  name:  'Angelo Maragna'

## note: 
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
path: https://angelomaragna.github.io
url:  'http://angelomaragna.github.io/'


########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

permalink: /:title.html

exclude:
- README.md


safe: true
lsi: false

